### ISSUE TITLE
Constant current source on Zynaptik board to make Pedal control short circuit proof

### ISSUE THREAD

**Issue by wyleu** [zynthian/zynthian-hw#8]
**Is your feature request related to a problem? Please describe.**
The zynaptik board seems specifically designed to accommodate control pedals, thus requiring a 5V ( the voltage of the ADS1115 module Full range) ring connection to the pedal ( Roland EV-5 et all).
If this is shorted even momentarily on connection the PI will depower, and reset at best.

**Describe the solution you'd like**
Add a constant current source to the zynaptik module that can be used as a known source ( aimed at 10K pots perhaps) that can limit if the supply is shorted.

**Describe alternatives you've considered**
Careful warning stikers et al... Normal functional acts shouldn't short out a supply rail.

.

**Comment by jofemodo** [comment]
I take note for the future Zynaptik version, but i just ordered 200 units of the Zynaptik v2, that includes everything SMD-soldered on board, so it will take a little bit.

**Comment by wyleu** [comment]
Observation in flight.

I've added a 100 Ohm resistor to the plus five volts feed to the pedals and I've got full scale deflection and shorting resistance... :-D

So probably close as knowledge.
