### ISSUE TITLE
Feature Request: Bigger ADAC

### ISSUE THREAD

**Issue by RussellAult** [zynthian/zynthian-hw#9]
Hi there!

Not sure if this is the place for this or not, but now that Zynthian is making its own ADAC boards, is there any chance we might see a multi-channel version in the future, perhaps along the lines of the (mostly open-source) [Elk Pi Hat](https://github.com/elk-audio/elk-pi-hardware/)?

Thanks!

**Comment by jofemodo** [comment]
Sorry @RussellAult , we have no plans for a multi-channel soundcard.
